------------------------------------------------------------------------------
-- Chimera API Bindings for SAPP
-- Sledmine
-- SAPP bindings for Chimera Lua functions, also EmmyLua helper
------------------------------------------------------------------------------